# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Chris Gumbsch
# Description of the Site
description: 
# URL of Image of the Site
site-image: https://raw.githubusercontent.com/cgumbsch/cgumbsch.github.io/master/assets/images/robo_emoji.png
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage) #https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940
heroimage: https://raw.githubusercontent.com/cgumbsch/cgumbsch.github.io/master/assets/images/art.png
# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: chris@gumbsch.de
facebook_username: 
twitter_username: cgumbsch
instagram_username:
linkedin_username: cgumbsch
github_username:  cgumbsch
youtube_channel_id: 
reddit_username: 
behance_username: 
dribbble_username: 
spotify_username: elgumbscho

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: thedevslot

# Name of the Author
author-name: Chris Gumbsch
# URL for the Image of the Author
author-image: https://raw.githubusercontent.com/cgumbsch/cgumbsch.github.io/master/assets/images/me_square.png
# 60 Words About the Author
author-about: Hi, I'm Christian Gumbsch. I'm a postdoc at the <a href="https://uni-tuebingen.de/fakultaeten/mathematisch-naturwissenschaftliche-fakultaet/fachbereiche/informatik/lehrstuehle/cognitive-modeling/">University of Tübingen</a> and the <a href=https://tu-dresden.de/mn/psychologie/ifap/kknw>TU Dresden</a> working with Martin Butz and Katharina von Kriegstein. Previously, I did my PhD in Cognitive Science at the <a href="https://al.is.mpg.de/">Max Planck Institute for Intelligent Systems</a> and <a href="https://uni-tuebingen.de/fakultaeten/mathematisch-naturwissenschaftliche-fakultaet/fachbereiche/informatik/lehrstuehle/cognitive-modeling/">University of Tübingen</a> jointly supervised by Georg Martius and Martin Butz.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/cgumbsch

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed
  - jemoji

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
